# Generated by Django 4.1.3 on 2022-11-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlayerModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(default=0)),
                ('y', models.IntegerField(default=0)),
                ('vx', models.IntegerField(default=0)),
                ('vy', models.IntegerField(default=0)),
                ('dead', models.BooleanField(default=False)),
                ('remove_heal', models.IntegerField(default=0)),
                ('orignal_heal', models.IntegerField(default=100)),
                ('turn', models.CharField(default='idle', max_length=20)),
                ('name', models.IntegerField(default='null', max_length=10)),
            ],
        ),
    ]
