# Generated by Django 4.1.3 on 2022-11-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_playermodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playermodel',
            name='name',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
