# Generated by Django 4.1.3 on 2022-12-14 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_alter_playermodel_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArenaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_red', models.IntegerField(default=0)),
                ('team_blue', models.IntegerField(default=0)),
                ('won', models.CharField(default='null', max_length=10)),
                ('player_1', models.CharField(default='null', max_length=20)),
                ('player_2', models.CharField(default='null', max_length=20)),
                ('player_3', models.CharField(default='null', max_length=20)),
                ('player_4', models.CharField(default='null', max_length=20)),
            ],
        ),
        migrations.RenameField(
            model_name='playermodel',
            old_name='name',
            new_name='player',
        ),
        migrations.RemoveField(
            model_name='playermodel',
            name='remove_heal',
        ),
        migrations.AddField(
            model_name='playermodel',
            name='color',
            field=models.CharField(default='blue', max_length=20),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='height',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='team',
            field=models.CharField(default='blue', max_length=10),
        ),
        migrations.AddField(
            model_name='playermodel',
            name='width',
            field=models.IntegerField(default=100),
        ),
    ]
