# Generated by Django 4.1.3 on 2022-12-14 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_arenamodel_rename_name_playermodel_player_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='playermodel',
            name='arena_id',
            field=models.IntegerField(default=0),
        ),
    ]
